### ISSUE TITLE
アイコン変更(バツ印、水道、湧水）

### ISSUE THREAD

**Issue by sugumura** [shinobushiva/Water#24]
マップに表示されるアイコン作成の募集です。

現状、水が出ない（赤）  水が出る（青）  水の提供可能（燈）  飲水不可（紫）で表示されたものをアイコンにできないかという提案です。

もし作ってもいいよ、という方がいらしたらコメントください。

※飲料不可はあとから追加されたものなので、イメージ提案なしの状態です #18

**Comment by kei4eva4** [comment]
データが増えてきて視認性が下がるため、現状のアイコンの色を見やすくする対応を行いました。
