### ISSUE TITLE
熊本市、宇土市 へのリンク追加

### ISSUE THREAD

**Issue by kashioka** [shinobushiva/Water#25]
断水解消や給水情報が上がるので、固定リンクを置く（熊本市緊急情報 http://www.city.kumamoto.jp/kinkyu/pub/default.aspx?c_id=3 宇土市 http://www.city.uto.kumamoto.jp/q/aview/61/13170.html）

固定リンクの件ですがニュースエリアができているのでそこに集約したいという意向

**Comment by kei4eva4** [comment]
ニュースエリアに追加しました。
