### ISSUE TITLE
漏水報告システムとの統合

### ISSUE THREAD

**Issue by eolla1013** [shinobushiva/Water#26]
Slackより転載。

熊本市上下水道局　宮崎様から連絡がありました。宮崎：ミズデルを見た。漏水ポイントが確認できるものを作ってもらえないか。
和泉：漏水報告サイトを紹介した　http://www.kyusui.net/rousui/
宮崎：地図上にプロットされていると、業者がわかりやすい
和泉：統合も含めいい感じになる方向で検討すると回答給水太郎氏（先の漏水報告サイト作者様、以前に連絡済み）にこちらに参加していただいて、機能統合できませんでしょうか？ユーザを漏水報告サイトに流入させるのは難しいと思うので、最初のページに、「水が出る/出ないを投稿」「漏水を登録する」のボタンを並べ、漏水を登録するの情報もトップのビューに統合。フィルタできるようにする。サイトアクセス時にポップアップで、熊本市より漏水報告の依頼を受けているとの内容を表示するなどでオフィシャルであることを明記。漏水報告は写真アップできるとよりよいです。
大掛かりな改修になりますけど、氏に参加いただくのが難しい場合は、こちらで作ってしまっても仕方ないかと思います。

**Comment by sugumura** [comment]
ご協力により、データインポート作業、水漏れのマップ表示が実装されました。
ありがとうございます。

クローズとします。
