### ISSUE TITLE
情報バルーンに解決済みボタンを追加する

### ISSUE THREAD

**Issue by sugumura** [shinobushiva/Water#30]
水漏れ（漏水）情報のみの対応。
# 担当者が、漏水箇所を確認後、解決済みとできるようなボタンを追加する。

解決済みボタンは、漏水アイコンクリック後の、情報バルーン内に設置する。

解決後はアイコンが変わる（緑地に白チェック）

**Comment by kei4eva4** [comment]
実装済み
