### ISSUE TITLE
ファイルアップロード・入力チェック

### ISSUE THREAD

**Issue by n1215** [shinobushiva/Water#31]
水漏れのPOST時の挙動について  
https://github.com/shinobushiva/Water/blob/master/webroot/rousui_post.php#L16-L23

コードを読んだ限りでは20MB以下のファイルなら何でもアップロードできそうですが、セキュリティは大丈夫ですか？  画像だけを許可するならS3へのアップロード前にリサイズをかけるなどしたほうが安全だと思います。

他のページも入力（$_GET、$_POST）の値のバリデーションは必ず行ったほうがいいです。スカラー値を意図しているところ配列が入ってくると処理の途中でエラーになる箇所が多そうに見えます。

**Comment by marcy-terui** [comment]
例によって完璧ではない暫定対応版投げておきました #32 

リサイズすれば明らかに画像じゃないやつはエラーになって、画像の中に不正なコードが仕込まれてる系はリサイズによって不正なコードが消えるからOKって感じでしたっけ？

リサイズ使う方法自体はなんとなく覚えていたものの、その効果と実装がどんな感じだったか思い出せない。。。

**Comment by kei4eva4** [comment]
ありがとうございます。#32マージしました。

入力バリデーションを実装するようにします。

**Comment by marcy-terui** [comment]
必要なバリデーションをとりあえずざっくり思いつくものから挙げておきます。
- 文字列かどうか（タイトルやコメント）
- 緯度経度の座標の形式にそっているか  
  正規表現だとこんな感じ？→ `/^\-?\d+\.\d+,.\d\.\d+$/`  
  ※`+`じゃなくて桁数を調べて`{1,3}`とかにできるとなお良い
- 不正な画像ファイルではないか（暫定対応済、リサイズを使った完成版）

**Comment by KeisukeUtsumi** [comment]
> 経緯度
> こちらはすでに対応済みですー。

不正ファイルの対応は
一旦全てjpegへの変換(オリジナルがjpegの場合は1回png経由)して、リサイズ(widthをmax640に設定？)
こんな感じでやろうと思ってますー。

まぁもっと細かい攻撃を意識しだすとキリがないので上記方針で問題がなければやっていこうと思いますー。

**Comment by marcy-terui** [comment]
足りないものや不備があれば後で直せば良いですし、手が空いていればやっちゃいましょう :-)

**Comment by KeisukeUtsumi** [comment]
https://bugs.php.net/bug.php?id=65536
おもいっきりlocalの環境でこれ踏みましたが、本番は5.6とのことで大丈夫だと信じます…。

**Comment by KeisukeUtsumi** [comment]
https://github.com/shinobushiva/Water/pull/38

PR出させてもらいましたん。
