### ISSUE TITLE
FacebookのWebView表示で位置情報が取得できない

### ISSUE THREAD

**Issue by sugumura** [shinobushiva/Water#34]
FacebookのiOSはplistにNSLocationWhenInUseUsageDescriptionの設定が無いため、WebView上で位置情報の取得ができていません。

そのため、navigator.geolocation.getCurrentPositionが失敗した場合、もしくはJSで取得できるUserAgentの「FBAN」などの文字列を判定しiOSでのFacebook/WebViewの場合は下記のアラートを出力する。

「Facebookアプリでは位置情報が取得できませんので、タイムラインのリンクを長押しし外部のブラウザで起動して下さい。」

参考
- http://stackoverflow.com/questions/25176750/location-service-in-uiwebview-on-ios8-beta-5-not-working
- http://lealog.hateblo.jp/entry/2014/10/09/130344

**Comment by syamn** [comment]
#41  で対応しました
