### ISSUE TITLE
ニュースの投稿に認証をかける

### ISSUE THREAD

**Issue by marcy-terui** [shinobushiva/Water#36]
ニュースの投稿は決まった人間しかしないはずなので、とりあえずBasic認証でもなんでも良いので認証をかけましょう。いたずらで投稿されるとそれが全員の目に触れてしまいますし、URLに悪意のあるサイトを登録されると非常にマズイです。

**Comment by marcy-terui** [comment]
`.ebextentions` で `/etc` かどっかに `.htpasswd` ファイル作って `.htaccess` でそれ使ってBasic認証かければPHP無しでいけると思うんでどなたかー

**Comment by n1215** [comment]
本番環境HTTPSじゃないようなのでDigest認証で書きました。
https://github.com/shinobushiva/Water/pull/42

**Comment by marcy-terui** [comment]
> 本番環境HTTPSじゃないようなのでDigest認証で書きました。

そういやそうですね。気の利いた対応で圧倒的感謝です :100:
