### ISSUE TITLE
漏水に関しては検索条件から除外する

### ISSUE THREAD

**Issue by eolla1013** [shinobushiva/Water#50]
漏水に関しては検索条件を除外する。

**Comment by sugumura** [comment]
df8d81d2939f8e41386d3728426ab72f08f8546e で実装されたため、クローズします。

**Comment by sugumura** [comment]
9dd386353d8ab473d355f0fdba13bca5def2b678 にて、漏水は時間フィルターはせずにチェックボックスによる表示・非表示のみ制御するようになりました。
