### ISSUE TITLE
Cookie無効で地図が表示されない。

### ISSUE THREAD

**Issue by kashioka** [shinobushiva/Water#52]
おつかれさまです
確認していて気づいたことがあるので一応issueにしておきます。
(対応決まったらクローズしていただいて結構です)

Cookie無効にするとTOPページでアクセスしたときに地図が表示されません。
また投稿時も地図が表示されないので投稿できないようです。

無効の場合の操作をどこまで許容するかですが
エラーメッセージ出す等の方が親切かなと思いました。

全体のポリシーにしたがって対応いただければと思います。

**Comment by marcy-terui** [comment]
私見ですが、商用サイトというわけではないので、そこまで親切にレアケースをケアしてあげる必要はないかなと思います。今どきCookie無効でまともに見れるサイトのほうが少ないので。

**Comment by kashioka** [comment]
そこらへんは踏まえた上でissue上げたのでその意見でも結構だと思います。
現地の状況がわからないので、どのような時にこのサイトを使うかなと思った時に、普段使わないPCからアクセスしたりとかもあるのかなと思ったの上げました。
報告もそうですが、水の出る状況を確認できるのが第一目的だと思ったので
